"use client";
import {useState} from "react";
import {Check,Info,Lightbulb,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Switch} from "@/components/ui/switch";
import {useDemo} from "@/components/dashboard/provider";
import {PageHeader,Panel,DemoInfo} from "@/components/dashboard/common";
import {policySchema,type Policy} from "@/lib/demo-policy";
import {money} from "@/lib/format";
export default function SettingsPage() {
  const d=useDemo();const [draft,setDraft]=useState<Policy>(d.policy);const [error,setError]=useState("");
  const dirty=JSON.stringify(draft)!==JSON.stringify(d.policy);
  function save(event:React.FormEvent) {event.preventDefault();const result=policySchema.safeParse(draft);if(!result.success){setError(result.error.issues[0].message);return;}d.savePolicy(result.data);setError("");d.notify("Demo settings saved. Forecast risk has been recalculated.");}
  return <><PageHeader title="Budget & policies" description="Set your limits. Decide how TokenGuard should respond."/>
  <form onSubmit={save} className="settings-form"><Panel title="Monthly budget" description="Your budget is a business decision, never a prediction."><div className="settings-grid"><div><Label htmlFor="budget">Monthly budget (MYR)</Label><Input id="budget" type="number" min="0.01" max="1000000" step="0.01" value={Number.isNaN(draft.budget)?"":draft.budget} onChange={e=>setDraft({...draft,budget:e.target.valueAsNumber})}/><p className="field-help">Calendar month · Asia/Kuala_Lumpur</p></div><div className="suggestion-box"><Lightbulb size={18}/><div><strong>Historical suggestion: {money(d.suggestion.amount)}</strong><p>Median of {d.suggestion.months} complete simulated months + 10% buffer.</p><Button variant="outline" size="sm" type="button" disabled={d.suggestion.amount===null} onClick={()=>{if(d.suggestion.amount!==null)setDraft({...draft,budget:d.suggestion.amount});}}>Use suggested budget</Button><span className="field-help">Applied to your draft only. Save to accept.</span></div></div></div></Panel>
  <Panel title="Optimisation mode" description="Control how future eligible requests should respond to risk."><fieldset><legend className="sr-only">Optimisation mode</legend><div className="mode-options">{([{value:"manual",title:"Manual",description:"Recommend changes. You decide what to approve."},{value:"adaptive",title:"Adaptive",description:"At risk, use only controls you have pre-approved."},{value:"always_on",title:"Always-on",description:"Use your selected safe controls at all risk levels."}] as const).map(mode=><label key={mode.value} className={`mode-option ${draft.mode===mode.value?"selected":""}`}><input type="radio" name="mode" value={mode.value} checked={draft.mode===mode.value} onChange={()=>setDraft({...draft,mode:mode.value})}/><strong>{mode.title}{mode.value==="adaptive"&&<span className="recommended-tag">Default</span>}</strong><p>{mode.description}</p></label>)}</div></fieldset><div className="info-note"><Info size={15}/><span>These settings preview policy behaviour. This demo cannot activate gateway optimisations.</span></div></Panel>
  <Panel title="Warning thresholds" description="Actual spending and month-end prediction have independent triggers."><div className="threshold-grid">{([{key:"preventive",label:"Preventive",description:"First actual-spend warning"},{key:"high",label:"High risk",description:"Actual-spend escalation"},{key:"critical",label:"Critical",description:"Urgent actual-spend warning"},{key:"predictive",label:"Predicted utilisation",description:"Early forecast warning"}] as const).map(t=><div key={t.key}><Label htmlFor={t.key}>{t.label} (%)</Label><Input id={t.key} type="number" min="1" max={t.key==="predictive"?1000:100} value={Number.isNaN(draft[t.key])?"":draft[t.key]} onChange={e=>setDraft({...draft,[t.key]:e.target.valueAsNumber})}/><p className="field-help">{t.description}</p></div>)}</div><p className="body-note">Actual thresholds must follow preventive &lt; high &lt; critical ≤ 100.</p></Panel>
  <Panel title="Approved controls" description="Safety exclusions always take priority over your selected mode."><div className="switch-row"><div><Label htmlFor="exact-cache">Safe exact FAQ cache</Label><p>Only explicitly eligible, stateless FAQs. Personal or multi-turn questions bypass caching.</p></div><Switch id="exact-cache" checked={draft.exactCache} onCheckedChange={checked=>setDraft({...draft,exactCache:checked})}/></div><div className="switch-row"><div><Label htmlFor="hard-stop">Stop new provider calls at the budget limit</Label><p>Opt-in preference for a future approximate cap. In-flight requests may still exceed the limit.</p></div><Switch id="hard-stop" checked={draft.hardStop} onCheckedChange={checked=>setDraft({...draft,hardStop:checked})}/></div><div className="disabled-controls"><ShieldCheck size={16}/><span>Semantic cache, model routing and output optimisation are deferred.</span></div></Panel>
  {error&&<div role="alert" className="form-error">{error}</div>}<div className="save-bar"><span>{dirty?"You have unsaved changes":"Your demo settings are up to date"}</span><div><Button type="button" variant="outline" disabled={!dirty} onClick={()=>{setDraft(d.policy);setError("");}}>Discard changes</Button><Button type="submit" disabled={!dirty}><Check size={16}/>Save changes</Button></div></div></form><DemoInfo/>
  </>;
}
