"use client";
import {CalendarClock,Coins,TrendingUp,Wallet,Info} from "lucide-react";
import {useDemo} from "@/components/dashboard/provider";
import {PageHeader,Stat,Panel,RiskBadge,DemoInfo} from "@/components/dashboard/common";
import {SpendingChart} from "@/components/dashboard/charts";
import {money,percent,shortDate} from "@/lib/format";
export default function ForecastPage() {
  const d=useDemo();const f=d.prediction;
  return <><PageHeader title="See the month ahead" description="Turn yesterday’s usage into an early signal for tomorrow’s decisions."/>
  <div className="forecast-summary"><div><span className="section-kicker">October month-end prediction</span><div className="forecast-big">{money(f.projected)}<span>projected</span></div><p>{percent(f.projectedPct)} of your {money(d.policy.budget)} budget · {money(f.overrun)} estimated overrun</p></div><div className="forecast-summary-side"><RiskBadge risk={d.risk}/><span>Rolling average · Simulated data</span><span>As of 10 October 2026</span></div></div>
  <div className="stats-grid"><Stat label="Observed month-to-date" value={money(f.actual)} note="Through 9 October" icon={Wallet}/><Stat label="Predicted remaining" value={money(f.remaining)} note={`${f.remainingDays} calendar days left`} icon={TrendingUp}/><Stat label="Daily baseline" value={money(f.dailyRate)} note={`Last ${f.historyDays} completed days`} icon={Coins}/><Stat label="Budget crossing" value={f.crossingDate?shortDate(f.crossingDate):"Not projected"} note="Estimate, not a guarantee" icon={CalendarClock}/></div>
  <Panel title="Actual spend meets the forecast" description="The dashed line extends the seven-day mean through the remaining month." action={<span className="method-chip">7-day rolling baseline</span>}><SpendingChart series={f.series} budget={d.policy.budget}/><div className="chart-caption">Actual utilisation {percent(f.actualPct)} · Forecast utilisation {percent(f.projectedPct)} · These values are never added together.</div></Panel>
  <div className="two-columns"><Panel title="How this prediction works" description="Transparent arithmetic. No LLM-generated numbers."><ol className="method-steps"><li><span>1</span><div><strong>Look back seven completed days</strong><p>The average provider cost is approximately {money(f.dailyRate)} per day.</p></div></li><li><span>2</span><div><strong>Project the remaining days</strong><p>Unrounded daily mean × {f.remainingDays} days = {money(f.remaining)}.</p></div></li><li><span>3</span><div><strong>Add observed monthly spending</strong><p>{money(f.actual)} + {money(f.remaining)} = {money(f.projected)}.</p></div></li></ol><div className="info-note"><Info size={15}/><span>{f.lowData?"Limited recent history. This fallback is low confidence.":"Assumes the recent spending rate continues. Future traffic, holidays and policy changes can alter the result."}</span></div></Panel>
  <Panel title="Check the baseline, honestly" description="Past-only rolling-origin backtest on synthetic history."><div className="backtest-metric"><span>Daily mean absolute error</span><strong>{money(d.backtest.mae)}</strong><p>{d.backtest.samples} held-out daily predictions · {d.usage.length} simulated days</p></div><p className="body-note">Each prediction uses only the preceding seven days. MAE measures average daily error in MYR; it is not an accuracy percentage or a month-end error.</p><div className="subtle-callout">This demonstrates the method on simulated data. It does not establish performance on real businesses. Ridge comparison is deferred.</div></Panel></div>
  <Panel title="Unusual spending" description="Days exceeding 1.8× their prior seven-day mean and RM5 above baseline."><div className="table-scroll"><table><thead><tr><th>Date</th><th className="numeric">Observed cost</th><th className="numeric">Prior daily baseline</th><th className="numeric">Spike ratio</th><th>Recommended next step</th></tr></thead><tbody>{d.spikes.map(s=><tr key={s.date}><td>{shortDate(s.date)}</td><td className="numeric">{money(s.cost)}</td><td className="numeric">{money(s.baseline)}</td><td className="numeric">{s.ratio.toFixed(1)}×</td><td>Review traffic and eligible caching</td></tr>)}</tbody></table></div>{d.spikes.length===0&&<p className="empty-text">No unusual spikes in this history.</p>}</Panel>
  <DemoInfo/>
  </>;
}
